FROM python:3.11

WORKDIR /app

COPY requirements.txt .

COPY ./tests /app/tests
COPY ./pytest.ini /app/pytest.ini

RUN pip install -r ./requirements.txt --no-cache-dir

CMD ["uvicorn", "v1.main:app", "--host", "0.0.0.0", "--port", "80"]