version: '3.3'
services:

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    
  api:
    build: .
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  test_db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_pytest_data:/var/lib/postgresql/data/
    command: -p 4321
    expose:
      - 4321
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}

  test:
    build:
      context: .
      dockerfile: Dockerfile_pytest
    env_file:
      - .env
    ports:
      - 9000:80
    container_name: fastapi_tests
    depends_on:
      - test_db
    command: sh -c "pytest -v"
    volumes:
      - .:/app
volumes:
  postgres_data:
  postgres_pytest_data: